### PR TITLE
Add constraint

### PR DESCRIPTION
**Pull request by DewarM**
Adds constraint prop (Defaults to false). This will not allow creation or movement outside of the child bounding box.

### CODE REVIEW

**Comment by davidlanger** [comment]
Thank you @DewarM :100:

**Comment by davidlanger** [comment]
@DewarM  re: RegionSelect styles. You aded `display: 'inline-block'`. Whats the reasoning behind that? B/c in our project this broke the display, so would like to remove (If needed for display in your project you can add custom styles via `styles` prop.

**Comment by DewarM** [comment]
Hi @davidlanger, this was basically to force the outer div to match the width of the underlying child element. You are totally correct though I can just add the it in the style prop. However, for the constraints to work correctly I believe this is necessary. 
I can add a flag, so when the constraint prop is true it adds the necessary display?
Revert as necessary and I'll see if I can fix in a separate pr, just let me know what is preferable!

**Comment by DewarM** [comment]
See #5 for possible fix.

**Pull request merged**
